language: node_js
node_js:
  - 7
  - 8
notifications:
  email:
    on_success: never
script:
  - npm run lint
  - npm run test
cache:
  directories:
    - node_modules
after_success:
  - npm run coveralls
